---
title: "Data Wrangling"
output: html_notebook
---

```{r}
# libraries
library(tidyverse)
library(haven)
library(data.table)
```

```{r}
# read data
cidi_raw <-
  fread("ukrmain_RU_061419.csv")
test_raw <-
  read_sav("AnalysisDatabaseForStat201.sav")
```

```{r}
# REPRODUCING THE FOUR CORE CONDITIONS
diag <-
  cidi_raw %>%
  mutate(affected_cher = ifelse(!is.na(dm40), dm40, de40),
         anx = ifelse(DSM_AGO == 1|DSM_SO == 1|DSM_GAD == 1, 1, 0),
         # bromet and bolt papers both include panic disorders in anxiety, 
         # but to match counts it's not included here. investigate.
         ied = ifelse(DSM_IEDH == 1, 1, 0),
         aff = ifelse(DSM_MDE == 1|DSM_DYS == 1, 1, 0),
         alc = ifelse(DSM_ALA == 1|DSM_ALD == 1, 1, 0)) %>%
  select(sampleid, affected_cher, anx, ied, aff, alc, weight1, secu, strata)
```

# Scrap Work

```{r}
# chern. q
cher_raw <-
  cidi_raw %>%
  mutate(affected_cher = ifelse(!is.na(dm40), dm40, de40),
         sampleid = as.numeric(sampleid)) %>%
  select(sampleid, AGE, affected_cher, secu, strata, weight1)
```

```{r}
# subset
diag <-
  diag_raw %>%
  mutate(sampleid = as.numeric(sampleid)) %>%
  left_join(cher_raw, by = "sampleid") %>%
  mutate(anx = ifelse((2002 - AGE + AGO_OND >= 1986) | 
                        (2002 - AGE + SO_OND >= 1986) |
                        (2002 - AGE + GAD_OND >= 1986) |
                        (2002 - AGE + PD_OND >= 1986), 1, 0),
         ied = ifelse(2002 - AGE + IED_OND >= 1986, 1, 0),
         aff = ifelse((2002 - AGE + MDE_OND >= 1986) | 
                        (2002 - AGE + DYS_OND >= 1986), 1, 0),
         alc = ifelse((2002 - AGE + ALA_OND >= 1986) | 
                        (2002 - AGE + ALD_OND >= 1986), 1, 0)) %>%
  select(sampleid, affected_cher, anx, ied, aff, alc, weight1, secu, strata)
```


